name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: plumber_schedule_dev
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.0'
    - name: Install dependencies
      run: |
        gem install bundler:2.3.11
        bundle install --jobs 4 --retry 3
    - name: Setup Database
      run: |
        cp config/database.yml.github-actions config/database.yml
        sudo service mysql start
        bundle exec rake db:create
        bundle exec rails db:migrate
      env:
        RAILS_ENV: test
    - name: Run Tests
      run: |
        bundle exec rspec
      env:
        DB_PORT: 3306
        RAILS_ENV: test