name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.0'

    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
    - name: Install dependencies
      run: |
        gem install bundler:2.3.11
        bundle install --jobs 4 --retry 3
      env:
        DB_PORT: 3306
        RAILS_ENV: test
    - name: Run Tests
      run: |
        bundle exec rspec
      env:
        DB_PORT: 3306
        RAILS_ENV: test