name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 2.6.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6.0'

    - name: Set up MySQL
      run: |
        sudo apt-get install -y mysql-client libmysqlclient-dev
        sudo /etc/init.d/mysql start
        mysql --host 127.0.0.1 --port 3306 -uroot -p
    - name: Install dependencies
      run: |
        gem install bundler:2.3.11
        bundle install --jobs 4 --retry 3
      env:
        DB_PORT: 3306
        RAILS_ENV: test
    - name: Run Tests
      run: |
        bundle exec rake db:create
        bundle exec rails db:migrate
        bundle exec rspec
      env:
        DB_PORT: 3306
        RAILS_ENV: test